// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIa-q2yZzujl0AriCH-_0t5DkRlEWgSxc',
    appId: '1:124991237466:web:42d0ad1669322b23641763',
    messagingSenderId: '124991237466',
    projectId: 'redee-b3df9',
    authDomain: 'redee-b3df9.firebaseapp.com',
    databaseURL: 'https://redee-b3df9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'redee-b3df9.appspot.com',
    measurementId: 'G-WDJCNK7YXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNnubCH9j_apmD-nHJiMl-X-o8T8yBH0Q',
    appId: '1:124991237466:android:f74b14f39ea66c46641763',
    messagingSenderId: '124991237466',
    projectId: 'redee-b3df9',
    databaseURL: 'https://redee-b3df9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'redee-b3df9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvkWARrw2ekn9J7-Mpfeh-g-tu5tBlTs',
    appId: '1:124991237466:ios:58fb981696262d2f641763',
    messagingSenderId: '124991237466',
    projectId: 'redee-b3df9',
    databaseURL: 'https://redee-b3df9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'redee-b3df9.appspot.com',
    iosClientId: '124991237466-fsb3nfgft5h32jq6im7cqolohr0j75il.apps.googleusercontent.com',
    iosBundleId: 'com.example.redeeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcvkWARrw2ekn9J7-Mpfeh-g-tu5tBlTs',
    appId: '1:124991237466:ios:6595ca5e0342b8be641763',
    messagingSenderId: '124991237466',
    projectId: 'redee-b3df9',
    databaseURL: 'https://redee-b3df9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'redee-b3df9.appspot.com',
    iosClientId: '124991237466-3cg9ie00k73hp00ak2l89el610hith2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.redeeApp.RunnerTests',
  );
}
